server:
  port: 8888 #项目启动访问端口
spring:
  main:
    allow-circular-references: true
  application:
    name: scm
  datasource: #连接数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scm_db?serverTimezone=UTC&amp;useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root
  servlet: #文件上传配置
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB